// Content for the landing page. Tokenized code strings are rendered with v-html.
// Keep any HTML below scoped to known-safe token spans (tok-*) — it is trusted
// authored content, not user input.

export interface IdeTab {
  id: string
  label: string
  filename: string
  iconClass: 'bpmn' | 'kt' | 'json'
  iconText: string
  paneType: 'image' | 'code'
  src?: string
  code?: string
}

export const ideTabs: IdeTab[] = [
  {
    id: 'bpmn',
    label: 'subscription.bpmn',
    filename: 'subscription.bpmn',
    iconClass: 'bpmn',
    iconText: '\u25C7',
    paneType: 'image',
    src: 'subscription.svg',
  },
  {
    id: 'api',
    label: 'SubscriptionProcessApi.kt',
    filename: 'SubscriptionProcessApi.kt',
    iconClass: 'kt',
    iconText: 'Kt',
    paneType: 'code',
    code: [
      `<span class="line"><span class="tok-c">// Generated by bpmn-to-code — do not edit</span></span>`,
      `<span class="line"><span class="tok-k">package</span> de.emaarco.subscription</span>`,
      `<span class="line"> </span>`,
      `<span class="line"><span class="tok-k">object</span> <span class="tok-t">SubscriptionProcessApi</span> {</span>`,
      `<span class="line">  <span class="tok-k">const val</span> PROCESS_ID: <span class="tok-t">String</span> = <span class="tok-s">"subscription"</span></span>`,
      `<span class="line">  <span class="tok-k">const val</span> PROCESS_ENGINE: <span class="tok-t">String</span> = <span class="tok-s">"ZEEBE"</span></span>`,
      `<span class="line"> </span>`,
      `<span class="line">  <span class="tok-k">object</span> <span class="tok-t">Elements</span> {</span>`,
      `<span class="line">    <span class="tok-k">const val</span> START_EVENT_SUBMIT_REGISTRATION_FORM: <span class="tok-t">String</span> = <span class="tok-s">"StartEvent_SubmitRegistrationForm"</span></span>`,
      `<span class="line">    <span class="tok-k">const val</span> SERVICE_TASK_INCREMENT_SUBSCRIPTION_COUNTER: <span class="tok-t">String</span> = <span class="tok-s">"serviceTask_incrementSubscriptionCounter"</span></span>`,
      `<span class="line">    <span class="tok-k">const val</span> SUB_PROCESS_CONFIRMATION: <span class="tok-t">String</span> = <span class="tok-s">"SubProcess_Confirmation"</span></span>`,
      `<span class="line">    <span class="tok-k">const val</span> ACTIVITY_SEND_CONFIRMATION_MAIL: <span class="tok-t">String</span> = <span class="tok-s">"Activity_SendConfirmationMail"</span></span>`,
      `<span class="line">    <span class="tok-k">const val</span> TIMER_EVERY_DAY: <span class="tok-t">String</span> = <span class="tok-s">"Timer_EveryDay"</span></span>`,
      `<span class="line">    <span class="tok-k">const val</span> END_EVENT_REGISTRATION_COMPLETED: <span class="tok-t">String</span> = <span class="tok-s">"EndEvent_RegistrationCompleted"</span></span>`,
      `<span class="line">  }</span>`,
      `<span class="line"> </span>`,
      `<span class="line">  <span class="tok-k">object</span> <span class="tok-t">Messages</span> {</span>`,
      `<span class="line">    <span class="tok-k">const val</span> MESSAGE_FORM_SUBMITTED: <span class="tok-t">String</span> = <span class="tok-s">"Message_FormSubmitted"</span></span>`,
      `<span class="line">  }</span>`,
      `<span class="line"> </span>`,
      `<span class="line">  <span class="tok-k">object</span> <span class="tok-t">Timers</span> {</span>`,
      `<span class="line">    <span class="tok-k">val</span> TIMER_EVERY_DAY: <span class="tok-t">BpmnTimer</span> = <span class="tok-t">BpmnTimer</span>(<span class="tok-s">"Duration"</span>, <span class="tok-s">"PT1M"</span>)</span>`,
      `<span class="line">  }</span>`,
      `<span class="line">}</span>`,
    ].join(''),
  },
  {
    id: 'test',
    label: 'SubscriptionRulesTest.kt',
    filename: 'SubscriptionRulesTest.kt',
    iconClass: 'kt',
    iconText: 'Kt',
    paneType: 'code',
    code: [
      `<span class="line"><span class="tok-k">class</span> <span class="tok-t">SubscriptionRulesTest</span> {</span>`,
      `<span class="line"> </span>`,
      `<span class="line">  <span class="tok-a">@Test</span></span>`,
      `<span class="line">  <span class="tok-k">fun</span> <span class="tok-s">\`subscription process passes architecture rules\`</span>() {</span>`,
      `<span class="line"> </span>`,
      `<span class="line">    <span class="tok-c">// when: validating the shared BPMN file</span></span>`,
      `<span class="line">    <span class="tok-k">val</span> result = <span class="tok-t">BpmnValidator</span></span>`,
      `<span class="line">      .fromClasspath(<span class="tok-s">"bpmn/subscription.bpmn"</span>)</span>`,
      `<span class="line">      .engine(<span class="tok-t">ProcessEngine</span>.<span class="tok-n">CAMUNDA_7</span>)</span>`,
      `<span class="line">      .withRules(</span>`,
      `<span class="line">        <span class="tok-t">BpmnRules</span>.<span class="tok-n">MISSING_SERVICE_TASK_IMPLEMENTATION</span>,</span>`,
      `<span class="line">        <span class="tok-t">BpmnRules</span>.<span class="tok-n">MISSING_MESSAGE_NAME</span>,</span>`,
      `<span class="line">        <span class="tok-t">BpmnRules</span>.<span class="tok-n">MISSING_ELEMENT_ID</span>,</span>`,
      `<span class="line">      )</span>`,
      `<span class="line">      .validate()</span>`,
      `<span class="line"> </span>`,
      `<span class="line">    <span class="tok-c">// then: no errors or violations</span></span>`,
      `<span class="line">    result.assertNoErrors()</span>`,
      `<span class="line">    result.assertNoViolations(<span class="tok-s">"missing-service-task-implementation"</span>)</span>`,
      `<span class="line">    result.assertNoViolations(<span class="tok-s">"missing-message-name"</span>)</span>`,
      `<span class="line">  }</span>`,
      `<span class="line">}</span>`,
    ].join(''),
  },
  {
    id: 'json',
    label: 'subscription.json',
    filename: 'subscription.json',
    iconClass: 'json',
    iconText: '{}',
    paneType: 'code',
    code: [
      `<span class="line">{</span>`,
      `<span class="line">  <span class="tok-s">"processId"</span>: <span class="tok-s">"subscription"</span>,</span>`,
      `<span class="line">  <span class="tok-s">"flowNodes"</span>: [</span>`,
      `<span class="line">    {</span>`,
      `<span class="line">      <span class="tok-s">"id"</span>: <span class="tok-s">"StartEvent_SubmitRegistrationForm"</span>,</span>`,
      `<span class="line">      <span class="tok-s">"displayName"</span>: <span class="tok-s">"Submit subscription form"</span>,</span>`,
      `<span class="line">      <span class="tok-s">"elementType"</span>: <span class="tok-s">"START_EVENT"</span>,</span>`,
      `<span class="line">      <span class="tok-s">"outgoing"</span>: [<span class="tok-s">"serviceTask_incrementSubscriptionCounter"</span>],</span>`,
      `<span class="line">      <span class="tok-s">"variables"</span>: [<span class="tok-s">"subscriptionId"</span>]</span>`,
      `<span class="line">    },</span>`,
      `<span class="line">    {</span>`,
      `<span class="line">      <span class="tok-s">"id"</span>: <span class="tok-s">"serviceTask_incrementSubscriptionCounter"</span>,</span>`,
      `<span class="line">      <span class="tok-s">"displayName"</span>: <span class="tok-s">"Increment subscription counter"</span>,</span>`,
      `<span class="line">      <span class="tok-s">"elementType"</span>: <span class="tok-s">"SERVICE_TASK"</span>,</span>`,
      `<span class="line">      <span class="tok-s">"outgoing"</span>: [<span class="tok-s">"SubProcess_Confirmation"</span>],</span>`,
      `<span class="line">      <span class="tok-s">"properties"</span>: {</span>`,
      `<span class="line">        <span class="tok-s">"type"</span>: <span class="tok-s">"ServiceTask"</span>,</span>`,
      `<span class="line">        <span class="tok-s">"implementationValue"</span>: <span class="tok-s">"counterClass"</span></span>`,
      `<span class="line">      }</span>`,
      `<span class="line">    }</span>`,
      `<span class="line">  ],</span>`,
      `<span class="line">  <span class="tok-s">"messages"</span>: [</span>`,
      `<span class="line">    { <span class="tok-s">"id"</span>: <span class="tok-s">"StartEvent_SubmitRegistrationForm"</span>, <span class="tok-s">"name"</span>: <span class="tok-s">"Message_FormSubmitted"</span> }</span>`,
      `<span class="line">  ]</span>`,
      `<span class="line">}</span>`,
    ].join(''),
  },
]

export const generateCompare = {
  before: [
    `<span class="cline"><span class="tok-c">// scattered across your codebase</span></span>`,
    `<span class="cline">client.newCreateInstanceCommand()</span>`,
    `<span class="cline">  .bpmnProcessId(<span class="tok-s">"newsletterSubscription"</span>)</span>`,
    `<span class="cline">  .send() <span class="tok-c">// typo? runtime error.</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline">client.newPublishMessageCommand()</span>`,
    `<span class="cline">  .messageName(<span class="tok-s">"Message_FormSubmitted"</span>)</span>`,
    `<span class="cline">  .send() <span class="tok-c">// renamed? silent failure.</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-a">@JobWorker</span>(type = <span class="tok-s">"newsletter.sendConfirmationMail"</span>)</span>`,
    `<span class="cline"><span class="tok-k">fun</span> sendConfirmationMail() { <span class="tok-c">/* ... */</span> }</span>`,
  ].join(''),
  after: [
    `<span class="cline"><span class="tok-k">import</span> <span class="tok-t">NewsletterSubscriptionProcessApi</span>.*</span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline">client.newCreateInstanceCommand()</span>`,
    `<span class="cline">  .bpmnProcessId(PROCESS_ID)</span>`,
    `<span class="cline">  .send() <span class="tok-c">// rename → compiler error.</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline">client.newPublishMessageCommand()</span>`,
    `<span class="cline">  .messageName(<span class="tok-t">Messages</span>.MESSAGE_FORM_SUBMITTED)</span>`,
    `<span class="cline">  .send()</span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-a">@JobWorker</span>(type = <span class="tok-t">TaskTypes</span>.NEWSLETTER_SEND_CONFIRMATION_MAIL)</span>`,
    `<span class="cline"><span class="tok-k">fun</span> sendConfirmationMail() { <span class="tok-c">/* ... */</span> }</span>`,
  ].join(''),
}

export const surfaceCompare = {
  before: [
    `<span class="cline"><span class="tok-k">&lt;bpmndi:BPMNShape</span> <span class="tok-a">id</span>=<span class="tok-s">"Event_12xytcj_di"</span></span>`,
    `<span class="cline">    <span class="tok-a">bpmnElement</span>=<span class="tok-s">"StartEvent_SubmitRegistrationForm"</span><span class="tok-k">&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;dc:Bounds</span> <span class="tok-a">x</span>=<span class="tok-s">"42"</span> <span class="tok-a">y</span>=<span class="tok-s">"302"</span> <span class="tok-a">width</span>=<span class="tok-s">"36"</span> <span class="tok-a">height</span>=<span class="tok-s">"36"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;bpmndi:BPMNLabel&gt;</span></span>`,
    `<span class="cline">    <span class="tok-k">&lt;dc:Bounds</span> <span class="tok-a">x</span>=<span class="tok-s">"16"</span> <span class="tok-a">y</span>=<span class="tok-s">"345"</span> <span class="tok-a">width</span>=<span class="tok-s">"88"</span> <span class="tok-a">height</span>=<span class="tok-s">"27"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;/bpmndi:BPMNLabel&gt;</span></span>`,
    `<span class="cline"><span class="tok-k">&lt;/bpmndi:BPMNShape&gt;</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-k">&lt;bpmndi:BPMNEdge</span> <span class="tok-a">id</span>=<span class="tok-s">"Flow_1csfyyz_di"</span><span class="tok-k">&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;di:waypoint</span> <span class="tok-a">x</span>=<span class="tok-s">"78"</span> <span class="tok-a">y</span>=<span class="tok-s">"320"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;di:waypoint</span> <span class="tok-a">x</span>=<span class="tok-s">"155"</span> <span class="tok-a">y</span>=<span class="tok-s">"320"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;di:waypoint</span> <span class="tok-a">x</span>=<span class="tok-s">"155"</span> <span class="tok-a">y</span>=<span class="tok-s">"200"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;di:waypoint</span> <span class="tok-a">x</span>=<span class="tok-s">"230"</span> <span class="tok-a">y</span>=<span class="tok-s">"200"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline"><span class="tok-k">&lt;/bpmndi:BPMNEdge&gt;</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-c">&lt;!-- ~200 more lines of diagram interchange --&gt;</span></span>`,
  ].join(''),
  after: [
    `<span class="cline">{</span>`,
    `<span class="cline">  <span class="tok-s">"id"</span>: <span class="tok-s">"StartEvent_SubmitRegistrationForm"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"displayName"</span>: <span class="tok-s">"Submit newsletter form"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"elementType"</span>: <span class="tok-s">"START_EVENT"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"outgoing"</span>: [<span class="tok-s">"Activity_IncrementCounter"</span>],</span>`,
    `<span class="cline">  <span class="tok-s">"messages"</span>: [<span class="tok-s">"Message_FormSubmitted"</span>]</span>`,
    `<span class="cline">},</span>`,
    `<span class="cline">{</span>`,
    `<span class="cline">  <span class="tok-s">"id"</span>: <span class="tok-s">"SubProcess_Confirmation"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"displayName"</span>: <span class="tok-s">"Subscription Confirmation"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"elementType"</span>: <span class="tok-s">"SUB_PROCESS"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"children"</span>: [<span class="tok-s">"Activity_SendConfirmationMail"</span>,</span>`,
    `<span class="cline">    <span class="tok-s">"Activity_ConfirmRegistration"</span>, <span class="tok-s">"Timer_EveryDay"</span>],</span>`,
    `<span class="cline">  <span class="tok-s">"outgoing"</span>: [<span class="tok-s">"Activity_SendWelcomeMail"</span>]</span>`,
    `<span class="cline">}</span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-c">// Nodes · flows · names. Nothing else.</span></span>`,
  ].join(''),
}

export interface RunnerRule {
  name: string
  hint: string
}

export const validateRules = {
  command: '$ ./gradlew test',
  fail: [
    { name: 'missing-service-task-implementation', hint: 'Service task <span class="tok-s">"Activity_SendWelcomeMail"</span> has no implementation.' },
    { name: 'missing-message-name', hint: 'Message on <span class="tok-s">"StartEvent_Submit"</span> has no name.' },
    { name: 'missing-element-id', hint: 'Gateway at row 3 has no id attribute.' },
    { name: 'service-task-naming', hint: 'Task <span class="tok-s">"incrementCounter"</span> should start with <span class="tok-s">"Activity_"</span>.' },
  ] as RunnerRule[],
  pass: [
    { name: 'missing-service-task-implementation', hint: 'All service tasks wired to a worker.' },
    { name: 'missing-message-name', hint: 'All messages named.' },
    { name: 'missing-element-id', hint: 'Every element has a stable id.' },
    { name: 'service-task-naming', hint: 'Naming convention enforced.' },
  ] as RunnerRule[],
}

export interface Skill {
  icon: string
  name: string
  description: string
}

export const skills: Skill[] = [
  {
    icon: '\u2708',
    name: 'create-process-service',
    description: 'Create a complete Spring Boot process service from a BPMN file — hexagonal layers, workers, Docker Compose, all wired to the generated Process API.',
  },
  {
    icon: '\u270E',
    name: 'build-bpmn-styleguide',
    description: 'Build a project-specific BPMN style guide with an interactive wizard, then let the agent validate every new diagram against it.',
  },
]
