version: 2
updates:

  # Config for all gradle dependencies.
  # This includes the plugin-core & the gradle-example(s)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      backend-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"

  # Config for all maven dependencies.
  # This includes only the maven-example(s)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      backend-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
