// Generated by bpmn-to-code
@file:Suppress("unused")

package io.github.emaarco.c7

import kotlin.String
import kotlin.Suppress

object NewsletterSubscriptionC7ProcessApi {
  const val PROCESS_ID: String = "newsletterSubscriptionC7"

  object Elements {
    const val Timer_EveryDay: String = "Timer_EveryDay"

    const val Timer_After3Days: String = "Timer_After3Days"

    const val ErrorEvent_InvalidMail: String = "ErrorEvent_InvalidMail"

    const val Activity_ConfirmRegistration: String = "Activity_ConfirmRegistration"

    const val SubProcess_Confirmation: String = "SubProcess_Confirmation"

    const val EndEvent_SubscriptionConfirmed: String = "EndEvent_SubscriptionConfirmed"

    const val EndEvent_RegistrationAborted: String = "EndEvent_RegistrationAborted"

    const val EndEvent_RegistrationCompleted: String = "EndEvent_RegistrationCompleted"

    const val EndEvent_RegistrationNotPossible: String = "EndEvent_RegistrationNotPossible"

    const val Activity_SendConfirmationMail: String = "Activity_SendConfirmationMail"

    const val Activity_AbortRegistration: String = "Activity_AbortRegistration"

    const val Activity_SendWelcomeMail: String = "Activity_SendWelcomeMail"

    const val StartEvent_SubmitRegistrationForm: String = "StartEvent_SubmitRegistrationForm"

    const val StartEvent_RequestReceived: String = "StartEvent_RequestReceived"
  }

  object Messages {
    const val Message_FormSubmitted: String = "Message_FormSubmitted"

    const val Message_SubscriptionConfirmed: String = "Message_SubscriptionConfirmed"
  }

  object TaskTypes {
    const val Activity_SendConfirmationMail: String = "newsletter.sendConfirmationMail"

    const val Activity_AbortRegistration: String = "newsletter.abortRegistration"

    const val Activity_SendWelcomeMail: String = "newsletter.sendWelcomeMail"

    const val EndEvent_RegistrationCompleted: String = "newsletter.registrationCompleted"
  }

  object Timers {
    val Timer_EveryDay: BpmnTimer = BpmnTimer("Duration", "PT1M")

    val Timer_After3Days: BpmnTimer = BpmnTimer("Duration", "PT2M30S")

    data class BpmnTimer(
      val type: String,
      val timerValue: String,
    )
  }

  object Signals {
    const val Signal_RegistrationNotPossible: String = "Signal_RegistrationNotPossible"
  }
}
