plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.mavenPublish)
    alias(libs.plugins.dokka)
    jacoco
}

group = "io.miragon"
version = property("projectVersion").toString()

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.bundles.testing)
    testRuntimeOnly(libs.junitPlatformLauncher)
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

mavenPublishing {

    publishToMavenCentral()
    if (project.hasProperty("signArtifacts")) signAllPublications()
    coordinates("io.miragon", "bpmn-to-code-runtime", version.toString())

    pom {
        name.set("bpmn-to-code-runtime")
        description.set("Shared runtime types for APIs generated by bpmn-to-code (ProcessId, ElementId, VariableName, ...)")
        inceptionYear.set("2026")
        url.set("https://github.com/emaarco/bpmn-to-code")
        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/licenses/MIT")
                distribution.set("https://opensource.org/licenses/MIT")
            }
        }
        developers {
            developer {
                id.set("emaarco")
                name.set("Marco Schaeck")
                url.set("https://github.com/emaarco")
            }
        }
        scm {
            url.set("https://github.com/emaarco/bpmn-to-code")
            connection.set("scm:git:git://github.com/emaarco/bpmn-to-code.git")
            developerConnection.set("scm:git:ssh://git@github.com/emaarco/bpmn-to-code.git")
        }
    }
}

// Backwards-compat: keep the old io.github.emaarco coordinate resolvable by publishing a
// relocation POM that redirects consumers to io.miragon. Removed in 4.0.
fun org.gradle.api.publish.maven.MavenPom.relocateTo(newGroupId: String, newArtifactId: String) {
    withXml {
        val relocation = asNode()
            .appendNode("distributionManagement")
            .appendNode("relocation")
        relocation.appendNode("groupId", newGroupId)
        relocation.appendNode("artifactId", newArtifactId)
        relocation.appendNode(
            "message",
            "The bpmn-to-code artifacts moved from the io.github.emaarco group to io.miragon as part " +
                "of the namespace migration. Update your dependency to $newGroupId:$newArtifactId.",
        )
    }
}

publishing {
    publications {
        register<MavenPublication>("relocation") {
            groupId = "io.github.emaarco"
            artifactId = "bpmn-to-code-runtime"
            version = project.version.toString()
            pom {
                name.set("bpmn-to-code-runtime (relocated)")
                description.set("Relocated to io.miragon:bpmn-to-code-runtime")
                relocateTo("io.miragon", "bpmn-to-code-runtime")
            }
        }
    }
}
