package io.github.emaarco.bpmn.adapter.outbound.codegen

import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.JavaProcessApiBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.KotlinProcessApiBuilder
import io.github.emaarco.bpmn.application.port.outbound.GenerateApiCodePort
import io.github.emaarco.bpmn.domain.BpmnModelApi
import io.github.emaarco.bpmn.domain.GeneratedApiFile
import io.github.emaarco.bpmn.domain.shared.OutputLanguage

class CodeGenerationAdapter(
    private val processApiBuilders: Map<OutputLanguage, AbstractProcessApiBuilder<*>> = Companion.processApiBuilders,
) : GenerateApiCodePort {

    override fun generateCode(modelApi: BpmnModelApi): List<GeneratedApiFile> {
        val language = modelApi.outputLanguage
        val processApiBuilder = processApiBuilders[language] ?: throw IllegalArgumentException("$language is not supported")
        val processFile = processApiBuilder.buildApiFile(modelApi)
        return listOf(processFile)
    }

    abstract class AbstractProcessApiBuilder<MainBuilder : Any> {
        abstract fun buildApiFile(modelApi: BpmnModelApi): GeneratedApiFile
        protected val autoGenComment = "Generated by bpmn-to-code"
    }

    companion object {
        val processApiBuilders = mapOf(
            OutputLanguage.KOTLIN to KotlinProcessApiBuilder(),
            OutputLanguage.JAVA to JavaProcessApiBuilder()
        )
    }

}
