name: Documentation Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/build-docs.yml'

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Enforce pinned npm dependencies
        uses: miragon/pin-npm-dependencies@v1
        with:
          root-path: docs

      - name: Install Dependencies
        run: npm ci
        working-directory: docs

      - name: Build Documentation
        run: npm run build
        working-directory: docs
