name: Publish to Gradle Plugin Portal

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build & Test
        run: ./gradlew build

      - name: Validate Plugin
        run: ./gradlew publishPlugins --validate-only

      - name: Publish Plugin
        run: ./gradlew publishPlugins
