package io.github.emaarco.bpmn.adapter.outbound.codegen

import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.JavaApiBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.KotlinApiBuilder
import io.github.emaarco.bpmn.application.port.outbound.GenerateApiCodePort
import io.github.emaarco.bpmn.domain.BpmnModelApi
import io.github.emaarco.bpmn.domain.GeneratedApiFile
import io.github.emaarco.bpmn.domain.shared.OutputLanguage

class CodeGenerationAdapter(
    private val builder: Map<OutputLanguage, AbstractApiBuilder<*>> = Companion.builder
) : GenerateApiCodePort {

    override fun generateCode(modelApi: BpmnModelApi): GeneratedApiFile {
        val outputLanguage = modelApi.outputLanguage
        val builder = builder[outputLanguage] ?: throw IllegalArgumentException("$outputLanguage is not supported")
        return builder.buildApiFile(modelApi)
    }

    abstract class AbstractApiBuilder<MainBuilder : Any> {
        abstract fun buildApiFile(modelApi: BpmnModelApi): GeneratedApiFile
        protected val autoGenComment = "Generated by bpmn-to-code"
    }

    companion object {
        val builder = mapOf(
            OutputLanguage.KOTLIN to KotlinApiBuilder(),
            OutputLanguage.JAVA to JavaApiBuilder()
        )
    }

}
