package io.github.emaarco.bpmn.adapter.outbound.codegen

import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.GoProcessApiBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.GoSharedTypesBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.JavaProcessApiBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.JavaSharedTypesBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.KotlinProcessApiBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.KotlinSharedTypesBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.TypeScriptProcessApiBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.TypeScriptSharedTypesBuilder
import io.github.emaarco.bpmn.application.port.outbound.GenerateApiCodePort
import io.github.emaarco.bpmn.domain.BpmnModelApi
import io.github.emaarco.bpmn.domain.GeneratedApiFile
import io.github.emaarco.bpmn.domain.shared.OutputLanguage

class CodeGenerationAdapter(
    private val processApiBuilders: Map<OutputLanguage, AbstractProcessApiBuilder<*>> = Companion.processApiBuilders,
    private val sharedTypesBuilders: Map<OutputLanguage, AbstractSharedTypesBuilder> = Companion.sharedTypesBuilders,
) : GenerateApiCodePort {

    override fun generateCode(modelApi: BpmnModelApi): List<GeneratedApiFile> {
        val language = modelApi.outputLanguage
        val processApiBuilder = processApiBuilders[language] ?: throw IllegalArgumentException("$language is not supported")
        val sharedTypesBuilder = sharedTypesBuilders[language] ?: throw IllegalArgumentException("$language is not supported")
        val processFile = processApiBuilder.buildApiFile(modelApi)
        val typeFiles = sharedTypesBuilder.buildTypeFiles(modelApi.packagePath, language)
        return listOf(processFile) + typeFiles
    }

    abstract class AbstractProcessApiBuilder<MainBuilder : Any> {
        abstract fun buildApiFile(modelApi: BpmnModelApi): GeneratedApiFile
        protected val autoGenComment = "Generated by bpmn-to-code"
    }

    abstract class AbstractSharedTypesBuilder {
        abstract fun buildTypeFiles(packagePath: String, language: OutputLanguage): List<GeneratedApiFile>
        protected val autoGenComment = "Generated by bpmn-to-code"
    }

    companion object {
        val processApiBuilders = mapOf(
            OutputLanguage.KOTLIN to KotlinProcessApiBuilder(),
            OutputLanguage.JAVA to JavaProcessApiBuilder(),
            OutputLanguage.TYPESCRIPT to TypeScriptProcessApiBuilder(),
            OutputLanguage.GO to GoProcessApiBuilder(),
        )
        val sharedTypesBuilders = mapOf(
            OutputLanguage.KOTLIN to KotlinSharedTypesBuilder(),
            OutputLanguage.JAVA to JavaSharedTypesBuilder(),
            OutputLanguage.TYPESCRIPT to TypeScriptSharedTypesBuilder(),
            OutputLanguage.GO to GoSharedTypesBuilder(),
        )
    }

}
