package io.github.emaarco.bpmn.adapter.outbound.codegen

import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.JavaApiBuilder
import io.github.emaarco.bpmn.adapter.outbound.codegen.builder.KotlinApiBuilder
import io.github.emaarco.bpmn.application.port.outbound.WriteApiFilePort
import io.github.emaarco.bpmn.domain.BpmnModel
import io.github.emaarco.bpmn.domain.BpmnModelApi
import io.github.emaarco.bpmn.domain.shared.OutputLanguage

class WriteApiFileAdapter(
    private val builder: Map<OutputLanguage, AbstractApiBuilder<*>> = Companion.builder
) : WriteApiFilePort {

    override fun writeApiFile(modelApi: BpmnModelApi) {
        val outputLanguage = modelApi.outputLanguage
        val builder = builder[outputLanguage] ?: throw IllegalArgumentException("$outputLanguage is not supported")
        builder.buildApiFile(modelApi)
    }

    abstract class AbstractApiBuilder<MainBuilder : Any> {
        abstract fun buildApiFile(modelApi: BpmnModelApi)
        protected abstract fun writeProcessId(builder: MainBuilder, model: BpmnModel)
        protected abstract fun writeElements(builder: MainBuilder, model: BpmnModel)
        protected abstract fun writeServiceTasks(builder: MainBuilder, model: BpmnModel)
        protected abstract fun writeMessages(builder: MainBuilder, model: BpmnModel)
        protected abstract fun writeSignals(builder: MainBuilder, model: BpmnModel)
        protected abstract fun writeErrors(builder: MainBuilder, model: BpmnModel)
        protected abstract fun writeTimers(builder: MainBuilder, model: BpmnModel)
        protected val autoGenComment = "Generated by bpmn-to-code"
    }

    companion object {
        val builder = mapOf(
            OutputLanguage.KOTLIN to KotlinApiBuilder(),
            OutputLanguage.JAVA to JavaApiBuilder()
        )
    }
}